### ISSUE TITLE
Errors in CQF Ruler when a new diagnosis is entered in Epic

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/htnu18ig#93]
Invalid Interval - the ending boundary must be greater than or equal to the starting boundary.
org.opencds.cqf.cql.engine.exception.InvalidInterval: Invalid Interval - the ending boundary must be greater than or equal to the starting boundary.
	at org.opencds.cqf.cql.engine.runtime.Interval.<init>(Interval.java:55)
	at org.opencds.cqf.cql.engine.elm.execution.IntervalEvaluator.internalEvaluate(IntervalEvaluator.java:20)
	at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:18)

This took a long time to track down since there was no context for what interval was being examined. But testing seems to indicate that the CQL cannot handle an onset period with a start date of today:

"onsetPeriod": {
     "start": "2021-10-21",
     "end": "2021-10-21"
}

When we saw this error previously, it always went away the next day, and I have tested setting the start to yesterday and the error is not thrown. Need to investigate more closely to see if the problem is in the CQL or in the engine.

**Comment by aeyates** [comment]
This error is reoccurring. When a problem list condition is first entered, it is not picked up by the recommendations. The next day, it is. The underlying problem is how CQL compares dates/datetimes. When there is a lack of information, it may return null. The author's guide gives this example:

Date(2014) < Date(2014, 2, 15)

In this case, the answer to the comparison is null because there are dates within the year 2014 that can be AFTER 2/15 and dates that can be BEFORE, so there is no answer. In our case, this is the comparison that is being made. The condition onset is a DATETIME, but Epic is only providing the date information:

DateTime(2022, 09, 14) <= Today()

The CQL interprets this as null too, indicating there is no answer because the time values on either side of the equation are  uncertain and could go either way. The simplest way to address this is just to add a day to Today():

DateTime(2022, 09, 14) <= Today() + 1 day

We can be pretty well assured that any datetime we read from Epic for condition onset/abatement will not be in the future, so this provides enough certainty for the comparison to evaluate properly.

**Comment by aeyates** [comment]
Never got confirmation that this was tested, but we'll call it good unless it comes up again.
